name: Publish

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GH_BUILD_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Cache scala dependencies
        uses: coursier/cache-action@v5
      - name: Publish
        run: sbt publish
