name: Publish

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GH_BUILD_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish
        run: sbt publish
